### PR TITLE
Add ascii() function

### PR DESCRIPTION
**Pull request by Thecode764**

### CODE REVIEW

**Comment by Mani4D46** [comment]
sorry but it has unclear names, please make the naming more clear

**Comment by Thecode764** [comment]
can change to ascii_art?

**Comment by Mani4D46** [comment]
that's better but not perfect maybe `to_ascii_art`

**Comment by Thecode764** [comment]
okay can you merge?

**Comment by Thecode764** [comment]
@Mani4D46

**Pull request merged**
