### PR TITLE
⬆️ Update requirements

### PR DESCRIPTION
**Pull request by Thecode764**

### CODE REVIEW

**Comment by Thecode764** [comment]
i dont have write access  :(((

**Comment by Mani4D46** [comment]
Sorry, can you check discord?

**Comment by Thecode764** [comment]
no sorry

**Comment by Thecode764** [comment]
i close this pr

**Comment by Mani4D46** [comment]
why?

**Comment by Thecode764** [comment]
idk :joy:

**Comment by Thecode764** [comment]
but my dns for discord isn't working

**Comment by Mani4D46** [comment]
Where can I message you then?

**Comment by Thecode764** [comment]
github issues. create a private rrpository and invite me open a issue!

**Comment by Thecode764** [comment]
*repository

**Comment by Mani4D46** [comment]
ok good idea
sent an invite

**Comment by Thecode764** [comment]
okay

**Comment by Thecode764** [comment]
i invited you to Thecode764/chat. please chebk you email

**Pull request closed without merging**
